### ISSUE TITLE
[1.17.1] Database Thread/ERROR Stacktrace - Server thread/ERROR Command exception: /market

### ISSUE THREAD

**Issue by Weeber2000** [Gunpowder-MC/GunpowderMarket#7]
![Screenshot 2021-10-02 081440](https://user-images.githubusercontent.com/91352794/135707374-35287e04-fc95-4e27-adc4-5a119fe37c3d.png)
Whenever we run /market it says "An unexpected error occurred trying to execute that command"

here are my logs - https://paste.shockbyte.com/ihifaqiduyogugeqibek

at line 1800 is where I run the /market command

all my mods are up to date and I have all gunpowder mods

**Comment by Martmists-GH** [comment]
It looks like there's an invalid item in the database, I recommend you remove it. Wouldn't know how you'd figure out which

**Comment by Weeber2000** [comment]
how can i remove the whole database or reset it

**Comment by Martmists-GH** [comment]
Removing the gunpowder.db file would be the easy way, but this resets everyone's money. 
Alternatively you could open the file in an sqlite viewer and remove all entries in the MarketEntry table.
